---
- name: install packages
  sudo: true
  apt: pkg={{ item }}
  with_items:
    - make
    - build-essential
    - libssl-dev
    - libc6-dev
    - libreadline6-dev
    - zlib1g-dev
    - libyaml-dev
    # - libmysql++-dev
    # - libsqlite3-dev

- name: git clone
  git: >
    repo={{ ruby_build.repo }}
    dest=/tmp/ruby-build

- name: install
  sudo: true
  command: >
    /tmp/ruby-build/install.sh
